name: Terraform CI/CD Pipeline

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: self-hosted

    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_USE_OIDC: true

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Check Azure Login
        run: az account show

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Verify Directory
        shell: powershell
        run: |
          pwd
          dir
          Get-ChildItem *.tf
          terraform version
        working-directory: terraform-modules/examples

      - name: Terraform Init
        shell: powershell
        run: |
          terraform init -upgrade -no-color
        working-directory: terraform-modules/examples

      - name: Terraform Validate
        shell: powershell
        run: |
          terraform validate -no-color
        working-directory: terraform-modules/examples

      - name: Terraform Plan
        shell: powershell
        run: |
          terraform plan -no-color -out=tfplan
        working-directory: terraform-modules/examples

      - name: Show Terraform Plan
        shell: powershell
        run: |
          dir tfplan
          terraform show -no-color tfplan
        working-directory: terraform-modules/examples

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        shell: powershell
        run: |
          terraform apply -auto-approve tfplan
        working-directory: terraform-modules/examples
